# Generated by Django 4.2.16 on 2024-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(editable=False, max_length=15, null=True, unique=True),
        ),
    ]
